### ISSUE TITLE
Web service invoiceCountRequest not working

### ISSUE THREAD

**Issue by arunpjohny** [arunpjohny/spring-ws-sample#1]
When the web service is requested it is throwing the following exception

```
org.springframework.ws.soap.client.SoapFaultClientException: argument type mismatch
    at org.springframework.ws.soap.client.core.SoapFaultMessageResolver.resolveFault(SoapFaultMessageResolver.java:37)
    at org.springframework.ws.client.core.WebServiceTemplate.handleFault(WebServiceTemplate.java:738)
    at org.springframework.ws.client.core.WebServiceTemplate.doSendAndReceive(WebServiceTemplate.java:564)
    at org.springframework.ws.client.core.WebServiceTemplate.sendAndReceive(WebServiceTemplate.java:502)
    at org.springframework.ws.client.core.WebServiceTemplate.marshalSendAndReceive(WebServiceTemplate.java:351)
    at org.springframework.ws.client.core.WebServiceTemplate.marshalSendAndReceive(WebServiceTemplate.java:345)
    at org.springframework.ws.client.core.WebServiceTemplate.marshalSendAndReceive(WebServiceTemplate.java:337)
    at com.arun.test.ws.invoice.InvoiceCountRequestTest.request(InvoiceCountRequestTest.java:27)
    at com.arun.test.ws.invoice.InvoiceCountRequestTest.main(InvoiceCountRequestTest.java:43)
```

**Comment by arunpjohny** [comment]
This issue is fixed.
The problem was with using the ObjectFactory class instead of jaxb.index
